<?php
/**
 * AutentizaceApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  BeLenka\Helios
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * iNuvio Server Auth API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.2.33
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace BeLenka\Helios\Test\Api;

use \BeLenka\Helios\Configuration;
use \BeLenka\Helios\ApiException;
use \BeLenka\Helios\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * AutentizaceApiTest Class Doc Comment
 *
 * @category Class
 * @package  BeLenka\Helios
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class AutentizaceApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiStatusGet
     *
     * Stav autentizačního serveru.
     *
     */
    public function testApiStatusGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTokenDelete
     *
     * Zneplatnění tokenu (a likvidace Runtime relace).
     *
     */
    public function testApiTokenDelete()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTokenGet
     *
     * Prodloužení expirace tokenu.
     *
     */
    public function testApiTokenGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for apiTokenPost
     *
     * Vytvoření nového tokenu (a Runtime relace).
     *
     */
    public function testApiTokenPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
